### PR TITLE
SSP MIS Revisions

### PR DESCRIPTION
**Pull request by bmaclach**
The MIS for SSP is ready for review, @smiths.

@Malavika-Srinivasan for your review, please look at the version of the document on the ssp_MIS branch.

### CODE REVIEW

**Comment by bmaclach** [comment]
Thanks @smiths. I've addressed some of the comments and asked follow-up questions to others here:  8d8f5904378e4329f73967ab2811edd8f8bb927c

**Comment by smiths** [comment]
@bmaclach, I'll review this work when I review the final documentation.

**Comment by bmaclach** [comment]
Okay @smiths, but if you don't mind, there was one question I hoped to get an answer to before submitting the final documentation. You suggested creating a module specifically for exporting types. I can do this, but I hesitate because I used the types in the MIS to make the MIS more readable, but the types do not actually exist in the implementation. Would it be okay to have a module that is not actually implemented by anything? Or perhaps somewhere in the MIS (the notation section, maybe) I can say something like "Throughout this document, 'coord' is used as shorthand for the type 'tuple of (x, y : R)'" and likewise for the other types?

**Comment by smiths** [comment]
Okay, I understand now.  I was reading the types as if they were exported.  If you relabel the sections where you introduce types as "local types" this will avoid confusion and let you use the types as you intended.

**Comment by bmaclach** [comment]
All right, thanks for the suggestion.

**Comment by smiths** [comment]
@bmaclach, I merged the final documentation.  Are the changes in this branch still necessary?

**Comment by bmaclach** [comment]
@smiths These changes were merged in with the final documentation.

**Comment by smiths** [comment]
@bmaclach, great to hear that the changes were merged.  Therefore, I will close this pull request.  If there is no new information in this branch, please go ahead and delete it, so that we don't need to wonder about it again in the future.

**Pull request closed without merging**
