### PR TITLE
SSP MG Revisions

### PR DESCRIPTION
**Pull request by bmaclach**
The MG for SSP is ready for review.

### CODE REVIEW

**Comment by bmaclach** [comment]
@karolserkis For your review of the SSP MG, please review the version on the "ssp_MG" branch of this repository. Thanks!

**Comment by smiths** [comment]
The review comments are given in e636348.
@bmaclach, have a look at the comments and make any changes you feel are necessary.  When the changes are made, we can merge this pull request.

**Comment by bmaclach** [comment]
Thanks @smiths. I made a few changes addressing the feedback in 
3fc037a.

**Comment by smiths** [comment]
The changes look great.  I'll merge this branch now.  You can delete the branch, assuming you are done with it.

**Pull request merged**
