### PR TITLE
Created implementations for the designs discussed.

### PR DESCRIPTION
**Pull request by B-rando1**
In order to help answer some of the questions raised [here](https://github.com/JacquesCarette/Drasil/issues/3752), I implemented the designs I listed [here](https://github.com/JacquesCarette/Drasil/wiki/File-Input-Patterns-Design-Discussion).

### CODE REVIEW

**Comment by smiths** [comment]
Having concrete code is a great way to see the different design options.  We can definitely merge this into the case studies repo.

**Comment by balacij** [comment]
Are we okay to delete the branch?

**Comment by smiths** [comment]
Good question @balacij.  @B-rando1 will you be doing any further development in this branch?

**Comment by B-rando1** [comment]
That's a good question @smiths.  Since there's likely to be some discussion on the designs here, there might be changes that need to be made.  I could set a reminder for after our Monday meeting to delete the branch if I'm not using it, does that sound good?

**Comment by smiths** [comment]
Sounds good, as long as you remember.  :smile:  Historically, we have had a bad habit of letting branches go unpruned.  :smile:

**Comment by JacquesCarette** [comment]
I fully intend to comment on the design. I've read it (it is nice and detailed) but commenting isn't a 2 minute job, so has to wait its turn in my priority queue.

**Pull request merged**
